kind: Namespace
apiVersion: v1
metadata:
  name: test
  labels:
    kubernetes.io/metadata.name: test
  annotations:
  #  argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-99"
    openshift.io/sa.scc.mcs: s0:c26,c5
    openshift.io/sa.scc.supplemental-groups: 1000660000/1000
    openshift.io/sa.scc.uid-range: 1000660000/1000
spec:
  finalizers:
    - kubernetes

