FROM quay.io/fedora/fedora:latest

# Create app directory
WORKDIR /tmp

USER root

RUN mkdir -p /workspace/output
RUN chown 1000:1000  /workspace && chown 1000:1000  /workspace/output
RUN chmod -R 0775 /workspace && chmod -R 0775 /workspace/output

COPY sh/* .


RUN dnf install git wget -y
RUN wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && chmod a+x /usr/local/bin/yq

USER 1000

ENV WORKENV=/workspace/output
ENV GIT='github.com/tal-hason/ArgoCICD-Demo.git'

ENTRYPOINT sh /tmp/update.sh