FROM quay.io/fedora/fedora:latest

# Create app directory
WORKDIR /tmp

USER root

RUN mkdir -p /workspace/output && \
    chown 1000:1000  /workspace && chown 1000:1000  /workspace/output && \
    chmod -R 0775 /workspace && chmod -R 0775 /workspace/output

COPY sh/* .


RUN dnf install git wget gzip zip unzip bzip2 -y && \
    wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && chmod a+x /usr/local/bin/yq && \
    dnf clean all && \
    useradd git -m --home-dir /home/git --gid 0 -s /bin/bash --uid 1000 && \
    mkdir /home/git/.docker && touch /home/git/.gitconfig && touch /home/git/.git-credentials && \
    chown -R 1000:0  /home/git && \
    chmod -R 0775 /home/git

USER 1000

