apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-cd-app
spec:
  destination:
    namespace: test
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: app/Application
    repoURL: 'https://github.com/tal-hason/ArgoCICD-Demo.git'
    targetRevision: main
  syncPolicy:
    automated: {}

