# Values for ArgoCD Application
application:
  name: ci-app
  namespace: openshift-gitops

imageupdater:
  image-list: 'quay.io/argocicd/hello-world'
  strategy: 'latest'

destination:
  namespace: test
  server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: app/yaml
    repoURL: 'https://github.com/tal-hason/ArgoCICD-Demo.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false

# Just testing 11

