apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.namespace }}
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  destination:
    namespace: {{ .Values.destination.namespace }}
    server: {{ .Values.destination.server }}
  project: {{ .Values.destination.project }}
  source:
    path: {{ .Values.destination.source.path }}
    repoURL: {{ .Values.destination.source.repoURL }}
    targetRevision: {{ .Values.destination.source.targetRevision }}
  syncPolicy:
    automated:
      prune: {{ .Values.destination.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.destination.syncPolicy.automated.selfHeal }}
    syncOptions:
      - CreateNamespace=true
