apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-cd-setting
  namespace: openshift-gitops
spec:
  destination:
    namespace: ci-cd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: app/yaml/Overlay/def
    repoURL: 'https://github.com/tal-hason/ArgoCICD-Demo.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
