kind: Service
apiVersion: v1
metadata:
  name: argocicd
  annotations:
     argocd.argoproj.io/sync-wave: "11"
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: argocicd
    deployment: argocicd

