kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "8"
  name: workspace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem


