apiVersion: batch/v1
kind: Job
metadata:
  generateName: git-clone-
spec:
  template:
    spec:
      serviceAccount: argocicd
      containers:
      - name: git-init
        env:
          - name: GIT
            valueFrom:
              configMapKeyRef:
                name: ci-cd-details
                key: git
          - name: WORKENV
            value: /workspace/output
        image: quay.io/argocicd/git-clone:v4
#        workingDir: /workspace/output
        volumeMounts:
        - name: workspace
          mountPath: /workspace/output
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: 'Always'
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: workspace
