kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workspace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv0027
  volumeMode: Filesystem

