apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
  name: step-1-git-clone
spec:
  template:
    spec:
      serviceAccount: argocicd
      restartPolicy: Never
      containers:
      - name: git-init
        env:
          - name: GIT
            valueFrom:
              configMapKeyRef:
                name: ci-cd-details
                key: git
          - name: WORKENV
            valueFrom:
              configMapKeyRef:
                name: ci-cd-details
                key: WORKENV
        image: quay.io/argocicd/git-clone:v6
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        securityContext:
          privileged: true
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: workspace
