apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- build-job.yaml
- clone-job.yaml
- Update-image.yaml

configMapGenerator:
- name: ci-cd-details
  envs:
  - https://raw.githubusercontent.com/tal-hason/ArgoCICD-Demo/main/Tools/config
#
# Change destination to promote from dev to drod
#
- name: promote
  literals:
    - destination=prod
#
# Git Clone scripit to inject to Pod
#
- name: git-clone
  files:
  - https://github.com/tal-hason/ArgoCICD-Demo/raw/main/Tools/git-clone/sh/git-clone.sh
#
# build-n-push scripit to inject to Pod
#
- name: build-n-push
  files:
  - https://github.com/tal-hason/ArgoCICD-Demo/raw/main/Tools/podman-build/sh/podman-b-n-p.sh
#
# update-deployscripit to inject to Pod
#
- name: update-deploy
  files:
  - https://github.com/tal-hason/ArgoCICD-Demo/raw/main/Tools/update-deploy/sh/update.sh


generatorOptions:
 disableNameSuffixHash: true
 annotations:
    argocd.argoproj.io/sync-wave: "0"
