apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- build-job.yaml
- clone-job.yaml

configMapGenerator:
- name: ci-cd-details
  files:
  - 

generatorOptions:
 disableNameSuffixHash: true
 annotations:
    argocd.argoproj.io/sync-wave: "0"
