apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- build-job.yaml
- clone-job.yaml

configMapGenerator:
- name: ci-cd-details
  namespace: test
  literals:	
  - git='https://github.com/tal-hason/ArgoCICD-Demo.git'
  - imagename=quay.io/argocicd/hello-world
  - imagetag='1.0.1'
  - path=app

generatorOptions:
 disableNameSuffixHash: true
 annotations:
    argocd.argoproj.io/sync-wave: "0"
