apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- build-job.yaml
- clone-job.yaml
- Update-image.yaml

configMapGenerator:
- name: ci-cd-details
  envs:
  - https://raw.githubusercontent.com/tal-hason/ArgoCICD-Demo/main/Tools/config
#
# Change destination to promote from dev to drod
#
- name: promote
  literals:
    - destination=prod

generatorOptions:
 disableNameSuffixHash: true
 annotations:
    argocd.argoproj.io/sync-wave: "0"
