apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base


patchesStrategicMerge:
- version.yaml

configMapGenerator:
- name: my-configmap
  literals:	
  - git='https://github.com/tal-hason/ArgoCICD-Demo.git'
  - imagename=quay.io/argocicd/hello-world
  - imagetag='1.2'
  - path=app

generatorOptions:
 disableNameSuffixHash: true
 annotations:
   annotations.only.for.generated: hello-world-app-config