apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "3"
  name: step-3-update-deploy
spec:
  template:
    spec:
      serviceAccount: argocicd
      restartPolicy: Never
      containers:
      - name: update-deploy
        env:
          - name: GIT
            valueFrom:
              configMapKeyRef:
                name: ci-cd-details
                key: git
          - name: WORKENV
            valueFrom:
              configMapKeyRef:
                name: ci-cd-details
                key: WORKENV
          # - name: TAG
          #   valueFrom:
          #     configMapKeyRef:
          #       name: ci-cd-details
          #       key: imagetag
          - name: NAME
            valueFrom:
              configMapKeyRef:
                name: ci-cd-details
                key: username
          - name: EMAIL
            valueFrom:
              configMapKeyRef:
                name: ci-cd-details
                key: email
          - name: COMMIT
            valueFrom:
              configMapKeyRef:
                name: ci-cd-details
                key: commit_message
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: gh-token
                key: TOKEN
          - name: ENV
            valueFrom:
              configMapKeyRef:
                name: promote
                key: destination
        image: quay.io/argocicd/update-deploy:v12
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        securityContext:
          privileged: true
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: workspace
