FROM quay.io/fedora/fedora:latest

# Create app directory
WORKDIR /tmp

USER root

RUN mkdir -p /workspace/output
RUN chown 1000:1000  /workspace && chown 1000:1000  /workspace/output
RUN chmod -R 0775 /workspace && chmod -R 0775 /workspace/output

COPY sh/* .



RUN dnf install git -y


USER 1000

ENV WORKENV=/workspace/output
ENV GIT='https://github.com/tal-hason/ArgoCICD-Demo.git'

ENTRYPOINT sh /tmp/git-clone.sh