FROM docker.io/fedora:36

# Create app directory
WORKDIR /tmp

USER root
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
RUN mkdir -p /workspace/output
RUN chown 1000:1000  /workspace && chown 1000:1000  /workspace/output
RUN chmod -R 0775 /workspace && chmod -R 0775 /workspace/output

COPY sh/* .


# update the base image
RUN dnf install git -y
# If you are building your code for production
# RUN npm ci --only=production

USER 1000

ENV WORKENV=/workspace/output
ENV GIT='https://github.com/tal-hason/ArgoCICD-Demo.git'

ENTRYPOINT sh /tmp/git-clone.sh