apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- name: ci-cd-details
  envs:
  - https://raw.githubusercontent.com/tal-hason/ArgoCICD-Demo/main/Tools/config

images:
- name: quay.io/argocicd/hello-world
  newName: 'quay.io/argocicd/hello-world'
  newTag: v1.17