apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- test1-job.yaml
- test2-job.yaml
- promote-to-prod.yaml

nameSuffix: -dev

configMapGenerator:
- name: ci-cd-details
  envs:
  - https://raw.githubusercontent.com/tal-hason/ArgoCICD-Demo/main/Tools/config.ini
- name: tag
  literals:
    - TAG=ver_668f5e
- name: tests
  files:
  - https://raw.githubusercontent.com/tal-hason/ArgoCICD-Demo/main/Tests/test1
  - https://raw.githubusercontent.com/tal-hason/ArgoCICD-Demo/main/Tests/test2
- name: scripts
  files:
  - https://raw.githubusercontent.com/tal-hason/ArgoCICD-Demo/main/Tools/git-clone/sh/git-clone.sh
  - https://raw.githubusercontent.com/tal-hason/ArgoCICD-Demo/main/Tools/update-deploy/sh/update.sh
images:
- name: quay.io/argocicd/hello-world
  newName: 'quay.io/argocicd/hello-world'
  newTag: ver_668f5e

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: argocicd
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
- target:
    kind: Route
    name: argocicd-dev
  patch: |-
    - op: replace
      path: /spec/to/name
      value: argocicd-dev