apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

nameSuffix: -dev

configMapGenerator:
- name: ci-cd-details
  envs:
  - https://raw.githubusercontent.com/tal-hason/ArgoCICD-Demo/main/Tools/config
- name: tag
  literals:
    - TAG=v1.27_GA

images:
- name: quay.io/argocicd/hello-world
  newName: 'quay.io/argocicd/hello-world'
  newTag: v1.27_GA

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: argocicd
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1