apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- name: ci-cd-details
  files:
  - imagename=https://raw.githubusercontent.com/tal-hason/ArgoCICD-Demo/main/Tools/config
  - imagetag=https://raw.githubusercontent.com/tal-hason/ArgoCICD-Demo/main/Tools/config


images:
- name: quay.io/argocicd/hello-world
  newName: 'quay.io/argocicd/hello-world'
  newTag: latest
