apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test
resources:
- ../../base


images:
- name: quay.io/argocicd/hello-world
  newName: 'quay.io/argocicd/hello-world'
  newTag: latest
