apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "3"
  name: promote-to-prod
spec:
  template:
    metadata:
      name: promote
    spec:
     restartPolicy: Never
     containers:
     - name: promote
       securityContext:
         privileged: true
       image: quay.io/argocicd/update-deploy:ne15
       workingDir: /workspace/output
       command: ["/bin/bash", "-c"]
       args:
       - /tmp/git-clone.sh
       - sleep 1
       - /tmp/update.sh
       env:
         - name: TEST2
           valueFrom:
             configMapKeyRef:
               name: tests
               key: test2
       volumeMounts:
       - name: workspace
         mountPath: /workspace/output
       - name: scripts
         mountPath: /tmp
     volumes:
      - name: workspace
        emptyDir: {}
      - name: scripts
        configMap:
         name: scripts
  backoffLimit: 1