apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "2"
  name: test-2-url
spec:
  template:
    metadata:
      name: test-url
    spec:
     restartPolicy: Never
     containers:
     - name: test-url
       image: registry.access.redhat.com/ubi9-minimal:latest
       workingDir: /workspace/output
       command: ["/bin/bash", "-c"]
       args: ["curl ${ARGOCICD_DEV_SERVICE_HOST}:${ARGOCICD_DEV_SERVICE_PORT}/test2 | grep ${TEST2} || exit 1"]
       env:
         - name: TEST2
           valueFrom:
             configMapKeyRef:
               name: tests
               key: test2
  backoffLimit: 1