FROM quay.io/podman/stable

# Create app directory
WORKDIR /tmp

USER root
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
RUN mkdir -p /workspace/output
RUN chown 1000:1000 -R /workspace/
RUN chmod -R 0777 /workspace/

COPY sh/* .

USER 1000

ENV WORKENV=/workspace/output
ENV GIT='https://github.com/tal-hason/ArgoCICD-Demo.git'
ENV LOC=/app
ENV IMAGE=thason/argocicd
ENV TAG=latset

ENTRYPOINT sh /tmp/podman-b-n-p.sh