apiVersion: batch/v1
kind: Job
metadata:
 name: podman-priv
spec:
  template:
    metadata:
      name: podman-test
    spec:
     serviceAccount: argocicd
     restartPolicy: Never
     containers:
     - name: priv
       image: quay.io/podman/stable
       workingDir: /workspace
       args:
       - sh
       - /workspace/Tools/podman-build/sh/podman-b-n-p.sh
       securityContext:
         privileged: true
       env:
         - name: IMAGE
           valueFrom:
             configMapKeyRef:
               name: ci-cd-details
               key: imagename
         - name: TAG
           valueFrom:
             configMapKeyRef:
               name: ci-cd-details
               key: imagetag
       volumeMounts:
       - name: workspace
         mountPath: /workspace
       - name: var
         mountPath: /var/lib/containers/
     volumes:
     - name: workspace
       persistentVolumeClaim:
         claimName: workspace
     - name: var
       emptyDir: {}