FROM docker.io/fedora:36

WORKDIR /tmp

USER root

RUN mkdir -p /workspace/output
RUN chown 1000:1000  /workspace && chown 1000:1000  /workspace/output
RUN chmod -R 0775 /workspace && chmod -R 0775 /workspace/output

RUN curl -sSL -o /tmp/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
RUN chmod +x /tmp/argocd

USER 1000

